namespace BitcoinCash.Core.Crypto
{
    /// <summary>
    /// The HMAC-SHA256 based deterministic random bit generator described by RFC 6979,
    /// which lets a private key and a message hash produce a signature nonce without
    /// relying on a random number source
    /// </summary>
    public sealed class RFC6979
    {
        private byte[] _v = new byte[32];
        private byte[] _k = new byte[32];
        private bool _retry;

        /// <summary>
        /// Seed the generator with the key material described in RFC 6979 section 3.2
        /// </summary>
        /// <param name="key">The concatenated private key, message hash and any extra entropy</param>
        public RFC6979(ReadOnlySpan<byte> key)
        {
            Array.Fill(_v, (byte)1);
            Array.Fill(_k, (byte)0);

            _k = Hashes.HMACSHA256(_k, [.. _v, 0x00, .. key]);
            _v = Hashes.HMACSHA256(_k, _v);

            _k = Hashes.HMACSHA256(_k, [.. _v, 0x01, .. key]);
            _v = Hashes.HMACSHA256(_k, _v);
        }

        /// <summary>
        /// Produce the next thirty two bytes of output
        /// </summary>
        /// <returns>The generated bytes</returns>
        public byte[] Generate()
        {
            if (_retry)
            {
                _k = Hashes.HMACSHA256(_k, [.. _v, 0x00]);
                _v = Hashes.HMACSHA256(_k, _v);
            }

            _v = Hashes.HMACSHA256(_k, _v);
            _retry = true;

            return (byte[])_v.Clone();
        }

        /// <summary>
        /// Derive the nonce for the given signing attempt, following the nonce function
        /// that libsecp256k1 and therefore Bitcoin Cash wallets use
        /// </summary>
        /// <param name="privateKey">The thirty two byte private key</param>
        /// <param name="hash">The thirty two byte message hash</param>
        /// <param name="extraEntropy">Optional thirty two bytes of additional data, used when grinding for a low R value</param>
        /// <param name="counter">How many outputs to discard before taking the nonce</param>
        /// <returns>The thirty two byte nonce</returns>
        public static byte[] GetNonce(ReadOnlySpan<byte> privateKey, ReadOnlySpan<byte> hash, byte[]? extraEntropy, uint counter)
        {
            var keyData = new byte[extraEntropy == null ? 64 : 96];

            privateKey.CopyTo(keyData);
            hash.CopyTo(keyData.AsSpan(32));
            extraEntropy?.CopyTo(keyData, 64);

            var generator = new RFC6979(keyData);

            var nonce = generator.Generate();

            for (var i = 0u; i < counter; i++)
                nonce = generator.Generate();

            return nonce;
        }
    }
}
