name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/davidshattuck/BitcoinCashClient
          azure-pipeline-name: "david-shattuck.BitcoinCashClient"
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
